export const MASTER_DATA = [
  { ID: "1.a.1", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.a Dokumen Perencanaan kinerja telah tersedia", Kriteria: "Terdapat pedoman teknis perencanaan kinerja", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0", Penjelasan: "Terdapat pedoman teknis perencanaan kinerja berupa Perbup dan/atau SOP yang telah ditetapkan oleh Pejabat yang berwenang." },
  { ID: "1.a.2", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.a Dokumen Perencanaan kinerja telah tersedia", Kriteria: "Terdapat dokumen perencanaan kinerja jangka panjang", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0", Penjelasan: "Terdapat pedoman teknis perencanaan kinerja berupa Perbup dan/atau SOP yang telah ditetapkan oleh Pejabat yang berwenang." },
  { ID: "1.a.3", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.a Dokumen Perencanaan kinerja telah tersedia", Kriteria: "Terdapat dokumen perencanaan kinerja jangka menengah", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0", Penjelasan: "Terdapat dokumen RPJMD/Renstra telah diformalkan (Dilengkapi tanggal, stempel dan tanda tangan)" },
  { ID: "1.a.4", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.a Dokumen Perencanaan kinerja telah tersedia", Kriteria: "Terdapat dokumen perencanaan kinerja jangka pendek", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0", Penjelasan: "Terdapat Dokumen RKPD/Renja sebagai Penjabaran RPJMD/Renstra yang telah ditetapkan oleh Pejabat yang berwenang" },
  { ID: "1.a.5", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.a Dokumen Perencanaan kinerja telah tersedia", Kriteria: "Terdapat dokumen perencanaan aktivitas yang mendukung kinerja", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0", Penjelasan: "Terdapat dokumen perencanaan aktivitas yang bersifat teknis dan operasional dalam mendukung pencapaian kinerja dan telah diformalkan" },
  { ID: "1.a.6", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.a Dokumen Perencanaan kinerja telah tersedia", Kriteria: "Terdapat dokumen perencanaan anggaran yang mendukung kinerja", Bobot: 0.5, Aturan_Nilai: "A=0.5, B=0.25, C=0", Penjelasan: "Terdapat dokumen RKA/DPA yang telah ditandatangani pejabat berwenang dan memuat indikator dan tolak ukur kinerja kegiatan secara lengkap meliputi capaian program, masukan, keluaran, dan hasil serta target kinerja" },
  { ID: "1.a.7", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.a Dokumen Perencanaan kinerja telah tersedia", Kriteria: "Setiap unit sataun kerja merumuskan dan menetapkan Perencanaan Kinerja", Bobot: 0.5, Aturan_Nilai: "A=0.5, B=0.25, C=0", Penjelasan: "Terdapat legalitas dokumen Perencanaan Kinerja Perangkat Daerah" },
  { ID: "1.b.1", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.b Dokumen Perencanaan kinerja telah memenuhi standar yang baik...", Kriteria: "Dokumen Perencanaan Kinerja telah diformalkan", Bobot: 0.5, Aturan_Nilai: "A=0.5, B=0.25, C=0", Penjelasan: "Dokumen perencanaan kinerja baik level Pemda maupun Perangkat Daerah telah diformalkan yang ditandatangani oleh Pejabat yang berwenang." },
  { ID: "1.b.2", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.b Dokumen Perencanaan kinerja telah memenuhi standar yang baik...", Kriteria: "Dokumen Perencanaan Kinerja telah dipublikasikan tepat waktu", Bobot: 0.5, Aturan_Nilai: "A=0.5, B=0.25, C=0", Penjelasan: "Dokumen Perencanaan Kinerja berupa RENSTRA, RENJA, IKU, Perjanjian Kinerja, Rencana Aksi, RKA/DPA, LKjIP dan lainnya dipublikasikan dalam website OPD/Pemda/di Diskominfo dan dalam Web e-SAKIP dengan alamat esr-Menpan.go.id." },
  { ID: "1.b.3", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.b Dokumen Perencanaan kinerja telah memenuhi standar yang baik...", Kriteria: "Dokumen Perencanaan Kinerja telah menggambarkan Kebutuhan atas Kinerja sebenarnya yang perlu dicapai", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0", Penjelasan: "Periksa keselarasan apakah semua unsur tersusun secara hierarkis dan saling mendukung mulai dari permasalahan → isu strategis → tujuan → sasaran → indikator → target kinerja dalam dokumen perencanaan kinerja sehingga menggambarkan kinerja yang perlu dicapai. Apakah sudah mencerminkan alur logika kinerja yang baik dan dapat ditindaklanjuti dalam rencana aksi atau Renja." },
  { ID: "1.b.4", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.b Dokumen Perencanaan kinerja telah memenuhi standar yang baik...", Kriteria: "Kualitas Rumusan Hasil (Tujuan/Sasaran) telah jelas menggambarkan kondisi kinerja", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0", Penjelasan: "Rumusan tujuan dan sasaran dalam dokumen perencanaan kinerja disusun dengan jelas dan tepat (spesifik, terukur dan fokus pada outcome tidak hanya pada ouput) sehingga menunjukkan dengan konkret kondisi yang ingin dicapai organisasi, dan dijabarkan secara konsisten dalam dokumen perencanaan kinerja" },
  { ID: "1.b.5", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.b Dokumen Perencanaan kinerja telah memenuhi standar yang baik...", Kriteria: "Ukuran Keberhasilan (Indikator Kinerja) telah memenuhi kriteria SMART", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0", Penjelasan: "Terdapat penilaian Indikator Kinerja (IKU, Indikator Program/Kegiatan) sesuai kriteria SMART yakni jelas dan fokus pada satu hasil tertentu (Spesific), dapat diukur secara obyektif (Measurabel), dapat dicapai (Achievabel), terkait langsung pada hasil (Relevant), untuk kurun waktu tertentu (Time bound)" },
  { ID: "1.b.6", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.b Dokumen Perencanaan kinerja telah memenuhi standar yang baik...", Kriteria: "Indikator Kinerja Utama (IKU) telah menggambarkan kondisi Kinerja Utama yang harus dicapai", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0", Penjelasan: "Membandingkan IKU dalam Renstra dituang secara berkelanjutan dalam kurun waktu 1 Periode Renstra (Tidak diubah setiap Tahun, IKU menyesuaikan dengan Renstra Murni atau Perubahan)" },
  { ID: "1.b.7", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.b Dokumen Perencanaan kinerja telah memenuhi standar yang baik...", Kriteria: "Target yang ditetapkan dalam Perencanaan Kinerja dapat dicapai (achievable), menantang, dan realistis", Bobot: 1, Aturan_Nilai: "A=1, B=0.75, C=0.5, D=0", Penjelasan: "Penetapan target indikator kinerja dalam Dokumen Perencanaan (Renstra, Renja, PK/SKP) ditetapkan berdasarkan baseline data yang jelas, dapat dicapai, menantang dan realistis serta dapat dipertanggungjawabkan" },
  { ID: "1.b.8", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.b Dokumen Perencanaan kinerja telah memenuhi standar yang baik...", Kriteria: "Setiap Dokumen Perencanaan Kinerja menggambarkan hubungan yang berkesinambungan, serta selaras antar level jabatan (Cascading)", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0.25, D=0", Penjelasan: "Terdapat diagram cascading yang menggambarkan hubungan yang berkesinambungan disetiap level jabatan mulai level pimpinan sampai jabatan paling rendah dan dokumen perencanaan kinerja disusun secara berjenjang dan terintegrasi dari RPJMD, Renstra, Renja dan PK hingga SKP" },
  { ID: "1.b.9", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.b Dokumen Perencanaan kinerja telah memenuhi standar yang baik...", Kriteria: "Perencanaan kinerja dapat memberikan informasi tentang hubungan kinerja, strategi, kebijakan, antar bidang (Crosscutting)", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0.25, D=0", Penjelasan: "Terdapat diagram crosscutting yang menggambarkan aktivitas antar bidang/unit internal dengan tugas dan fungsi instansi lainnya" },
  { ID: "1.b.10", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.b Dokumen Perencanaan kinerja telah memenuhi standar yang baik...", Kriteria: "Setiap unit/satuan kerja merumuskan dan menetapkan Perencanaan Kinerja", Bobot: 0.5, Aturan_Nilai: "A=0.5, B=0.25, C=0", Penjelasan: "Kepala Perangkat Daerah dan setiap level Jabatan Struktural menetapkan Perjanjian Kinerja secara berjenjang dan saling memiliki keterkaitan sesuai jenjang jabatan (Eselon II s.d Eselon IV)" },
  { ID: "1.b.11", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.b Dokumen Perencanaan kinerja telah memenuhi standar yang baik...", Kriteria: "Setiap pegawai merumuskan dan menetapkan Perencanaan Kinerja", Bobot: 0.5, Aturan_Nilai: "A=0.5, B=0.25, C=0", Penjelasan: "Setiap level Jabatan Fungsional Tertentu/Jabatan Fungsional Umum menetapkan Sasaran Kinerja Pegawai (SKP) yang mengacu dan mempunyai keketerkaitan dengan atasan langsung" },
  { ID: "1.c.1", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.c Perencanaan Kinerja telah dimanfaatkan untuk mewujudkan hasil...", Kriteria: "Anggaran yang ditetapkan telah mengacu pada Kinerja yang ingin dicapai", Bobot: 2, Aturan_Nilai: "A=2, B=1, C=0.5, D=0", Penjelasan: "Alokasi Anggaran dalam Program/kegiatan/sub kegiatan dalam RKA/DPA harus relevan dengan prioritas kebutuhan kinerja (anggaran diprioritaskan untuk mendukung kinerja utama yang ingin dicapai/ berdampak pada pencapaian target kinerja)" },
  { ID: "1.c.2", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.c Perencanaan Kinerja telah dimanfaatkan untuk mewujudkan hasil...", Kriteria: "Aktivitas yang dilaksanakan telah mendukung Kinerja yang ingin dicapai", Bobot: 2, Aturan_Nilai: "A=2, B=1, C=0.5, D=0", Penjelasan: "Periksa Rencana Aksi apakah sudah memuat program, kegiatan/sub kegiatan yang menunjang pencapaian sasaran strategis dan target kinerja yang ingin dicapai." },
  { ID: "1.c.3", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.c Perencanaan Kinerja telah dimanfaatkan untuk mewujudkan hasil...", Kriteria: "Target yang ditetapkan dalam Perencanaan Kinerja telah dicapai dengan baik, atau masih on the right track", Bobot: 2, Aturan_Nilai: "A=2, B=1, C=0.5, D=0", Penjelasan: "Terdapat informasi ketercapaian target kinerja per triwulan dalam Rencana Aksi yang ditetapkan selaras dengan target kinerja yang ditetapkan dalam dokumen perencanaan kinerja sehingga dapat terpantau target kinerja yang sudah tercapai dan masih berproses." },
  { ID: "1.c.4", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.c Perencanaan Kinerja telah dimanfaatkan untuk mewujudkan hasil...", Kriteria: "Rencana aksi kinerja dapat berjalan dinamis karena capaian kinerja selalu dipantau secara berkala", Bobot: 2, Aturan_Nilai: "A=2, B=1, C=0.5, D=0", Penjelasan: "Apakah dilakukannya Monev setiap triwulan untuk memastikan adanya realiasasi target kinerja program, kegiatan dan sub kegiatan pada Rencana Aksi yang dituangkan dalam Laporan Monev dan ditandatangani pejabat terkait." },
  { ID: "1.c.5", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.c Perencanaan Kinerja telah dimanfaatkan untuk mewujudkan hasil...", Kriteria: "Terdapat perbaikan/penyempurnaan Dokumen Perencanaan Kinerja dari hasil analisis perbaikan kinerja sebelumnya", Bobot: 2, Aturan_Nilai: "A=2, B=1, C=0.5, D=0", Penjelasan: "Penjabaran kendala atau hambatan atas kinerja atau target yang tidak tercapai pada tahun sebelumnya dalam LKjIP menjadi langkah perbaikan yang tertuang di RKPD atau Renja-PD" },
  { ID: "1.c.6", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.c Perencanaan Kinerja telah dimanfaatkan untuk mewujudkan hasil...", Kriteria: "Terdapat perbaikan/penyempurnaan Dokumen Perencanaan Kinerja dalam mewujudkan kondisi/hasil yang lebih baik", Bobot: 2, Aturan_Nilai: "A=2, B=1, C=0.5, D=0", Penjelasan: "Dokumen Perencanaan telah memuat perbaikan/penyempurnaan untuk peningkatan kinerja yang lebih baik seperti inovasi, penambahan program kinerja, atau penyesuaian target kinerja." },
  { ID: "1.c.7", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.c Perencanaan Kinerja telah dimanfaatkan untuk mewujudkan hasil...", Kriteria: "Setiap unit/satuan kerja memahami dan peduli, serta berkomitmen dalam mencapai kinerja yang telah direncanakan", Bobot: 2, Aturan_Nilai: "A=2, B=1, C=0.5, D=0", Penjelasan: "Terdapat penilaian kinerja esselon 2, esselon 3 dan esselon 4 pelaksanaan dari Perjanjian Kinerja yang dilaporkan setiap bulan melalui aplikasi e-Kinerja sebagai wujud komitmen dalam pencapaian target kinerja dan penggunaan anggaran" },
  { ID: "1.c.8", Komponen: "PERENCANAAN KINERJA", SubKomponen: "1.c Perencanaan Kinerja telah dimanfaatkan untuk mewujudkan hasil...", Kriteria: "Setiap Pegawai memahami dan peduli, serta berkomitmen dalam mencapai kinerja yang telah direncanakan", Bobot: 1, Aturan_Nilai: "A=1, B=0.75, C=0.5, D=0.25, E=0", Penjelasan: "Setiap pegawai melaksanakan Sasaran Kinerja Pegawai dan mendapat penilaian atas hasil kerja yang dilaporkan dalam aplikasi e-kinerja setiap bulan sebagai wujud komitmen dalam mendukung pencapaian target kinerja secara berjenjang" },
  { ID: "2.a.1", Komponen: "PENGUKURAN KINERJA", SubKomponen: "2.a Pengukuran Kinerja telah dilakukan", Kriteria: "Terdapat pedoman teknis pengukuran kinerja dan pengumpulan data kinerja", Bobot: 2, Aturan_Nilai: "A=2, B=1, C=0.5, D=0", Penjelasan: "Terdapat pedoman teknis pengukuran kinerja dan pengumpulan data kinerja yang telah diformalkan" },
  { ID: "2.a.2", Komponen: "PENGUKURAN KINERJA", SubKomponen: "2.a Pengukuran Kinerja telah dilakukan", Kriteria: "Terdapat Definisi Operasional yang jelas atas kinerja dan cara mengukur indikator kinerja", Bobot: 2, Aturan_Nilai: "A=2, B=1, C=0.5, D=0", Penjelasan: "Terdapat dokumen manual indikator yang memuat definisi operasional secara formal atas indikator kinerja strategis dan Indikator Program dengan minimal memuat narasi yang menjelaskan: 1. Judul Indikator Kinerja 2.tujuan 3. Definisi Operasional/Deskripsi 4. formulasi pengukuran 5. sumber data 6. periode pengukuran dan penanggung jawabnya" },
  { ID: "2.a.3", Komponen: "PENGUKURAN KINERJA", SubKomponen: "2.a Pengukuran Kinerja telah dilakukan", Kriteria: "Terdapat mekanisme yang jelas terhadap pengumpulan data kinerja yang dapat diandalkan", Bobot: 2, Aturan_Nilai: "A=2, B=1, C=0.5, D=0", Penjelasan: "Terdapat SOP yang menggambarkan secara jelas mekanisme pengumpulan data kinerja yang digunakan untuk semua indikator kinerja yang tercantum dalam Renstra/Renja dan/atau IKU, serta kejelasan penanggung jawab dari setiap level Indikator Kinerja" },
  { ID: "2.b.1", Komponen: "PENGUKURAN KINERJA", SubKomponen: "2.b Pengukuran Kinerja telah menjadi kebutuhan dalam mewujudkan Kinerja secara Efektif dan Efisien", Kriteria: "Pimpinan selalu teribat sebagai pengambil keputusan (Decision Maker) dalam mengukur capaian", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0.25, D=0", Penjelasan: "Pimpinan selalu memimpin rapat proses monitoring dan evaluasi capaian kinerja bulanan atau per triwulan dan memberikan langkah korektif untuk peningkatan kinerja,dan juga menandatangani Daftar Hadir, Notulen evaluasi kinerja sebagai bentuk pertanggungjawaban." },
  { ID: "2.b.2", Komponen: "PENGUKURAN KINERJA", SubKomponen: "2.b Pengukuran Kinerja telah menjadi kebutuhan dalam mewujudkan Kinerja secara Efektif dan Efisien", Kriteria: "Data kinerja yang dikumpulkan telah relevan untuk mengukur capaian kinerja yang diharapkan", Bobot: 2, Aturan_Nilai: "A=2, B=1, C=0.5, D=0", Penjelasan: "Terdapat sumber data pengukuran kinerja yang akuntabel sesuai dengan tujuan dan sasaran yang ingin dicapai dalam IKU dengan memperhatikan Definisi Operasional indikator outcome" },
  { ID: "2.b.3", Komponen: "PENGUKURAN KINERJA", SubKomponen: "2.b Pengukuran Kinerja telah menjadi kebutuhan dalam mewujudkan Kinerja secara Efektif dan Efisien", Kriteria: "Data kinerja yang dikumpulkan telah mendukung capaian kinerja yang diharapkan", Bobot: 2, Aturan_Nilai: "A=2, B=1, C=0.5, D=0", Penjelasan: "Output yang dihasilkan secara langsung atau tidak langsung telah mendukung atau berkontribusi pada tercapainya outcome yang diharapkan." },
  { ID: "2.b.4", Komponen: "PENGUKURAN KINERJA", SubKomponen: "2.b Pengukuran Kinerja telah menjadi kebutuhan dalam mewujudkan Kinerja secara Efektif dan Efisien", Kriteria: "Pengukuran kinerja telah dilakukan secara berkala", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0.25, D=0", Penjelasan: "Pengukuran kinerja dilakukan per triwulan dan terjadwal atas indikator kinerja utama maupun kinerja pendukung" },
  { ID: "2.b.5", Komponen: "PENGUKURAN KINERJA", SubKomponen: "2.b Pengukuran Kinerja telah menjadi kebutuhan dalam mewujudkan Kinerja secara Efektif dan Efisien", Kriteria: "Setiap level organisasi melakukan pemantauan atas pengukuran capaian kinerja unit dibawahnya secara berjenjang", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0.25, D=0", Penjelasan: "Pengukuran kinerja dilakukan per triwulan dan terjadwal untuk seluruh bidang/bagian yang terdiri atas capaian kinerja Program, capaian kinerja kegiatan/Sub Kegiatan." },
  { ID: "2.b.6", Komponen: "PENGUKURAN KINERJA", SubKomponen: "2.b Pengukuran Kinerja telah menjadi kebutuhan dalam mewujudkan Kinerja secara Efektif dan Efisien", Kriteria: "Pengumpulan data kinerja telah memanfaatkan Teknologi Informasi (Aplikasi)", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0.25, D=0", Penjelasan: "Terdapat aplikasi yang digunakan untuk pengumpulan data kinerja" },
  { ID: "2.b.7", Komponen: "PENGUKURAN KINERJA", SubKomponen: "2.b Pengukuran Kinerja telah menjadi kebutuhan dalam mewujudkan Kinerja secara Efektif dan Efisien", Kriteria: "Pengukuran capaian kinerja telah memanfaatkan Teknologi Informasi (Aplikasi)", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0.25, D=0", Penjelasan: "Terdapat aplikasi yang digunakan untuk pengukuran data kinerja" },
  { ID: "2.c.1", Komponen: "PENGUKURAN KINERJA", SubKomponen: "2.c Pengukuran Kinerja telah dijadikan dasar dalam pemberian Reward dan Punishment", Kriteria: "Pengukuran Kinerja telah menjadi dasar dalam penyesuaian (pemberian/pengurangan) tunjangan kinerja/penghasilan", Bobot: 2, Aturan_Nilai: "A=2, B=1, C=0.5, D=0", Penjelasan: "Terdapat pembayaran tunjangan berdasarkan pengukuran kinerja bulanan melalui e-kinerja dan absensi elektronik" },
  { ID: "2.c.2", Komponen: "PENGUKURAN KINERJA", SubKomponen: "2.c Pengukuran Kinerja telah dijadikan dasar dalam pemberian Reward dan Punishment", Kriteria: "Pengukuran Kinerja telah menjadi dasar dalam penempatan/penghapusan Jabatan baik struktural maupun fungsional", Bobot: 2, Aturan_Nilai: "A=2, B=1, C=0.5, D=0", Penjelasan: "Terdapat regulasi yang mengatur penempatan dan pergerakan pegawai yakni mutasi, rotasi, promosi, demosi, hingga pemberhentian yang didasarkan pada hasil atau capaian kinerja Pegawai (Pedoman pelaksanaan Sistem Merit)" },
  { ID: "2.c.3", Komponen: "PENGUKURAN KINERJA", SubKomponen: "2.c Pengukuran Kinerja telah dijadikan dasar dalam pemberian Reward dan Punishment", Kriteria: "Pengukuran kinerja telah mempengaruhi penyesuaian (Refocusing) Organisasi", Bobot: 2, Aturan_Nilai: "A=2, B=1, C=0.5, D=0", Penjelasan: "Terdapat penyesuaian target dan anggaran dampak dari kebijakan nasional atau Pemda dan juga dari hasil Monev kinerja triwulan sehingga dokumen perencanaan kinerja mengalami pergeseran atau perubahan" },
  { ID: "2.c.4", Komponen: "PENGUKURAN KINERJA", SubKomponen: "2.c Pengukuran Kinerja telah dijadikan dasar dalam pemberian Reward dan Punishment", Kriteria: "Pengukuran kinerja telah mempengaruhi penyesuaian Strategi dalam mencapai kinerja", Bobot: 2, Aturan_Nilai: "A=2, B=1, C=0.5, D=0", Penjelasan: "Berdasarkan hasil Monev pengukuran Kinerja Per Triwulan dan informasi realisasi anggaran apakah terdapat kinerja yang tidak mencapai target, jika ada hambatan dalam pencapaiannya maka faktor penyebabnya akan menjadi dasar penentuan penyesuaian strategi pencapaian kinerja dalam tahun berjalan" },
  { ID: "2.c.5", Komponen: "PENGUKURAN KINERJA", SubKomponen: "2.c Pengukuran Kinerja telah dijadikan dasar dalam pemberian Reward dan Punishment", Kriteria: "Pengukuran kinerja telah mempengaruhi penyesuaian Kebijakan dalam mencapai kinerja", Bobot: 2, Aturan_Nilai: "A=2, B=1, C=0.5, D=0", Penjelasan: "Hasil Monev pengukuran kinerja per triwulan dan jika ada instruksi efisiensi belanja dari Pemerintah menjadi dasar Kepala Daerah atau Kepala Perangkat Daerah membuat penyesuaian kebijakan melalui refocusing anggaran yang dilaksanakan melalui RKPD/Renja Pergeseran/Perubahan." },
  { ID: "2.c.6", Komponen: "PENGUKURAN KINERJA", SubKomponen: "2.c Pengukuran Kinerja telah dijadikan dasar dalam pemberian Reward dan Punishment", Kriteria: "Pengukuran kinerja telah mempengaruhi penyesuaian Aktivitas dalam mencapai kinerja", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0", Penjelasan: "Hasil Monev Pengukuran Kinerja Per triwulan serta dampak dari adanya kebijakan efisiensi belanja/refocusing mempengaruhi penyesuaian aktivitas yang dianggarkan dalam program/kegiatan/sub kegiatan serta penyesuaian target kinerja" },
  { ID: "2.c.7", Komponen: "PENGUKURAN KINERJA", SubKomponen: "2.c Pengukuran Kinerja telah dijadikan dasar dalam pemberian Reward dan Punishment", Kriteria: "Pengukuran kinerja telah mempengaruhi penyesuaian Anggaran dalam mencapai kinerja", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0", Penjelasan: "Hasil Monev pengukuran Kinerja Per Triwulan menjadi dasar penyesuaian anggaran dalam mencapai kinerja pada tahun berjalan" },
  { ID: "2.c.8", Komponen: "PENGUKURAN KINERJA", SubKomponen: "2.c Pengukuran Kinerja telah dijadikan dasar dalam pemberian Reward dan Punishment", Kriteria: "Terdapat efisiensi atas penggunaan anggaran dalam mencapai kinerja", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0.25, D=0", Penjelasan: "Terdapat informasi efisiensi anggaran yang dilengkapi analisis perbandingan tingkat ketercapaian target dan realisasi kinerja dengan rencana dan realisasi anggaran yang digunakan" },
  { ID: "2.c.9", Komponen: "PENGUKURAN KINERJA", SubKomponen: "2.c Pengukuran Kinerja telah dijadikan dasar dalam pemberian Reward dan Punishment", Kriteria: "Setiap unit/satuan kerja memahami dan peduli atas hasil pengukuran kinerja", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0", Penjelasan: "Terdapat pengukuran/penilaian kinerja seluruh pejabat struktural setiap bulan" },
  { ID: "2.c.10", Komponen: "PENGUKURAN KINERJA", SubKomponen: "2.c Pengukuran Kinerja telah dijadikan dasar dalam pemberian Reward dan Punishment", Kriteria: "Setiap pegawai memahami dan peduli atas hasil pengukuran kinerja", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0", Penjelasan: "Terdapat pengukuran/penilaian kinerja seluruh pegawai fungsional/pelaksana setiap bulan" },
  { ID: "3.a.1", Komponen: "PELAPORAN KINERJA", SubKomponen: "3.a Terdapat Dokumen Laporan yang menggambarkan Kinerja", Kriteria: "Dokumen Laporan Kinerja telah disusun", Bobot: 0.5, Aturan_Nilai: "A=0.5, B=0", Penjelasan: "LKj periode yang dievaluasi telah disusun dan final serta disahkan oleh Pejabat berwenang" },
  { ID: "3.a.2", Komponen: "PELAPORAN KINERJA", SubKomponen: "3.a Terdapat Dokumen Laporan yang menggambarkan Kinerja", Kriteria: "Dokumen Laporan Kinerja telah disusun secara berkala", Bobot: 0.5, Aturan_Nilai: "A=0.5, B=0", Penjelasan: "Terdapat Dokumen LKj secara formal yang disusun berdasarkan periode perencanaan" },
  { ID: "3.a.3", Komponen: "PELAPORAN KINERJA", SubKomponen: "3.a Terdapat Dokumen Laporan yang menggambarkan Kinerja", Kriteria: "Dokumen Laporan Kinerja telah diformalkan", Bobot: 0.5, Aturan_Nilai: "A=0.5, B=0.25, C=0", Penjelasan: "Laporan Kinerja telah ditandatangani oleh kepala OPD dilengkapi dengan stempel, nomor laporan atau tanda tangan elektronik" },
  { ID: "3.a.4", Komponen: "PELAPORAN KINERJA", SubKomponen: "3.a Terdapat Dokumen Laporan yang menggambarkan Kinerja", Kriteria: "Dokumen Laporan Kinerja telah direviu", Bobot: 0.5, Aturan_Nilai: "A=0.5, B=0.25, C=0", Penjelasan: "Laporan Kinerja telah di reviu/verifikasi kebenaran isinya oleh atasan secara berjenjang sebelum ditanda tangani dan dilengkapi surat pernyataan/Surat Keterangan telah direviu" },
  { ID: "3.a.5", Komponen: "PELAPORAN KINERJA", SubKomponen: "3.a Terdapat Dokumen Laporan yang menggambarkan Kinerja", Kriteria: "Dokumen Laporan Kinerja telah dipublikasikan", Bobot: 0.5, Aturan_Nilai: "A=0.5, B=0.25, C=0", Penjelasan: "Dokumen LKj telah dipublikasikan di Website resmi OPD/Pemda/Kominfo atau media lain yang dapat diakses dengan mudah setiap saat oleh publik serta di Website e-SAKIP MENPANRB dengan alamat esr.menpan.go.id" },
  { ID: "3.a.6", Komponen: "PELAPORAN KINERJA", SubKomponen: "3.a Terdapat Dokumen Laporan yang menggambarkan Kinerja", Kriteria: "Dokumen Laporan Kinerja telah disampaikan tepat waktu", Bobot: 0.5, Aturan_Nilai: "A=0.5, B=0", Penjelasan: "LKj Pemda disampaikan kepada MenPANRB paling lambat 31 Maret. Dan LKj OPD disampaikan kepada KDH melalui Bagian organisasi paling lambat 2 bulan setelah TA berakhir atau sesuai deadline yang ditentukan dalam Surat Edaran dibuktikan dengan ekspedisi/ surat pengantar/tanda terima pengiriman dan screenshoot telah Diupload kedalam aplikasi e-SAKIP Menpan paling lambat Per 31 Maret." },
  { ID: "3.b.1", Komponen: "PELAPORAN KINERJA", SubKomponen: "3.b Dokumen Laporan Kinerja telah memenuhi Standar menggambarkan Kualitas atas Pencapaian Kinerja", Kriteria: "Dokumen Laporan Kinerja disusun secara berkualitas sesuai dengan standar", Bobot: 0.5, Aturan_Nilai: "A=0.5, B=0.25, C=0", Penjelasan: "Laporan Kinerja disusun sesuai sistematika yang diatur dalam PermenPAN Nomor 53 tahun 2014 (Sistematika menyesuaikan jika ada regulasi baru)." },
  { ID: "3.b.2", Komponen: "PELAPORAN KINERJA", SubKomponen: "3.b Dokumen Laporan Kinerja telah memenuhi Standar menggambarkan Kualitas atas Pencapaian Kinerja", Kriteria: "Dokumen Laporan Kinerja telah mengungkap seluruh informasi tentang pencapaian kinerja", Bobot: 0.5, Aturan_Nilai: "A=0.5, B=0", Penjelasan: "Dalam LKj memuat seluruh indikator, target dan realisasi kinerja utama dan pendukung termasuk realisasi anggaran" },
  { ID: "3.b.3", Komponen: "PELAPORAN KINERJA", SubKomponen: "3.b Dokumen Laporan Kinerja telah memenuhi Standar menggambarkan Kualitas atas Pencapaian Kinerja", Kriteria: "Dokumen Laporan Kinerja telah menginfokan perbandingan realisasi kinerja dengan target tahunan", Bobot: 0.5, Aturan_Nilai: "A=0.5, B=0", Penjelasan: "Terdapat data perbandingan realisasi kinerja dengan target tahunan" },
  { ID: "3.b.4", Komponen: "PELAPORAN KINERJA", SubKomponen: "3.b Dokumen Laporan Kinerja telah memenuhi Standar menggambarkan Kualitas atas Pencapaian Kinerja", Kriteria: "Dokumen Laporan Kinerja telah menginfokan perbandingan realisasi kinerja dengan target jangka menengah", Bobot: 0.5, Aturan_Nilai: "A=0.5, B=0", Penjelasan: "Terdapat informasi target RENSTRA diperbandingkan dengan realisasi kinerja pada tahun evaluasi" },
  { ID: "3.b.5", Komponen: "PELAPORAN KINERJA", SubKomponen: "3.b Dokumen Laporan Kinerja telah memenuhi Standar menggambarkan Kualitas atas Pencapaian Kinerja", Kriteria: "Dokumen Laporan Kinerja telah menginfokan perbandingan realisasi kinerja dengan realisasi kinerja tahun-tahun sebelumnya", Bobot: 0.5, Aturan_Nilai: "A=0.5, B=0.25, C=0", Penjelasan: "Terdapat data realisasi kinerja tahun evaluasi diperbandingkan dengan capaian kinerja 2 tahun sebelumnya atau lebih" },
  { ID: "3.b.6", Komponen: "PELAPORAN KINERJA", SubKomponen: "3.b Dokumen Laporan Kinerja telah memenuhi Standar menggambarkan Kualitas atas Pencapaian Kinerja", Kriteria: "Dokumen Laporan Kinerja telah menginfokan perbandingan realisasi kinerja dengan realiasi kinerja di level nasional/internasional", Bobot: 0.5, Aturan_Nilai: "A=0.5, B=0", Penjelasan: "Terdapat perbandingan target dan realisasi kinerja OPD dengan target dan realisasi kinerja tingkat Provinsi / Nasional" },
  { ID: "3.b.7", Komponen: "PELAPORAN KINERJA", SubKomponen: "3.b Dokumen Laporan Kinerja telah memenuhi Standar menggambarkan Kualitas atas Pencapaian Kinerja", Kriteria: "Dokumen Laporan Kinerja telah menginfokan kualitas atas capaian kinerja beserta upaya nyata dan/atau hambatannya", Bobot: 0.5, Aturan_Nilai: "A=0.5, B=0", Penjelasan: "Dalam Laporan Kinerja terdapat informasi data capaian kinerja beserta uraian keberhasilan, kegagalan, upaya nyata mencapai target kinerja dan hambatan pelaksanaan" },
  { ID: "3.b.8", Komponen: "PELAPORAN KINERJA", SubKomponen: "3.b Dokumen Laporan Kinerja telah memenuhi Standar menggambarkan Kualitas atas Pencapaian Kinerja", Kriteria: "Dokumen Laporan Kinerja telah menginfokan efisiensi atas penggunaan sumber daya dalam mencapai kinerja", Bobot: 0.5, Aturan_Nilai: "A=0.5, B=0", Penjelasan: "Terdapat informasi tentang efektivitas dan efisiensi penggunaan sumber daya (orang, anggaran, sarana prasarana)" },
  { ID: "3.b.9", Komponen: "PELAPORAN KINERJA", SubKomponen: "3.b Dokumen Laporan Kinerja telah memenuhi Standar menggambarkan Kualitas atas Pencapaian Kinerja", Kriteria: "Dokumen Laporan Kinerja telah menginfokan upaya perbaikan dan penyempurnaan kinerja ke depan (Rekomendasi perbaikan kinerja)", Bobot: 0.5, Aturan_Nilai: "A=0.5, B=0", Penjelasan: "Dalam laporan kinerja mengungkapkan informasi upaya perbaikan dan penyempurnaan kinerja ke depan" },
  { ID: "3.c.1", Komponen: "PELAPORAN KINERJA", SubKomponen: "3.c Pelaporan Kinerja telah memberikan dampak yang besar dalam penyesuaian strategi/kebijakan", Kriteria: "Informasi dalam laporan kinerja selalu menjadi perhatian utama pimpinan (Bertanggung Jawab)", Bobot: 1.5, Aturan_Nilai: "A=1.5, B=1, C=0", Penjelasan: "Rapat penetapan kinerja dalam LKj dan Monev progres kinerja selalu dihadiri dan ditandatangani oleh Kepala Perangkat Daerah" },
  { ID: "3.c.2", Komponen: "PELAPORAN KINERJA", SubKomponen: "3.c Pelaporan Kinerja telah memberikan dampak yang besar dalam penyesuaian strategi/kebijakan", Kriteria: "Penyajian informasi dalam laporan kinerja menjadi kepedulian seluruh pegawai", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0.25, D=0", Penjelasan: "Terdapat rapat internal Bidang untuk pembahasan capaian kinerja, dan seluruh pegawai (PNS & PPPK) memberikan informasi realisasi target kinerja dalam SKP" },
  { ID: "3.c.3", Komponen: "PELAPORAN KINERJA", SubKomponen: "3.c Pelaporan Kinerja telah memberikan dampak yang besar dalam penyesuaian strategi/kebijakan", Kriteria: "Informasi dalam laporan kinerja berkala telah digunakan dalam penyesuaian aktivitas untuk mencapai kinerja", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0", Penjelasan: "Periksa apakah informasi dalam laporan kinerja berkala (triwulanan) telah digunakan dalam penyesuaian aktivitas untuk mencapai kinerja." },
  { ID: "3.c.4", Komponen: "PELAPORAN KINERJA", SubKomponen: "3.c Pelaporan Kinerja telah memberikan dampak yang besar dalam penyesuaian strategi/kebijakan", Kriteria: "Informasi dalam laporan kinerja berkala telah digunakan dalam penyesuaian penggunaan anggaran untuk mencapai kinerja", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0", Penjelasan: "Periksa apakah informasi dalam laporan kinerja berkala (triwulanan) telah digunakan dalam penyesuaian penggunaan anggaran untuk mencapai kinerja." },
  { ID: "3.c.5", Komponen: "PELAPORAN KINERJA", SubKomponen: "3.c Pelaporan Kinerja telah memberikan dampak yang besar dalam penyesuaian strategi/kebijakan", Kriteria: "Informasi dalam laporan kinerja telah digunakan dalam evaluasi pencapaian keberhasilan kinerja", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0", Penjelasan: "Periksa apakah informasi dalam laporan kinerja berkala (triwulanan) telah digunakan dalam penyesuaian penggunaan anggaran untuk mencapai kinerja." },
  { ID: "3.c.6", Komponen: "PELAPORAN KINERJA", SubKomponen: "3.c Pelaporan Kinerja telah memberikan dampak yang besar dalam penyesuaian strategi/kebijakan", Kriteria: "Informasi dalam laporan kinerja telah digunakan dalam penyesuaian perencanaan kinerja yang akan dihadapi berikutnya", Bobot: 1, Aturan_Nilai: "A=1, B=0", Penjelasan: "Capaian Target Kinerja, hambatan dan rekomendasi perbaikan kinerja dalam laporan kinerja Tahun sebelumnya ditindaklanjuti dalam perencanaan kinerja tahun berikutnya" },
  { ID: "3.c.7", Komponen: "PELAPORAN KINERJA", SubKomponen: "3.c Pelaporan Kinerja telah memberikan dampak yang besar dalam penyesuaian strategi/kebijakan", Kriteria: "Informasi dalam laporan kinerja selalu mempengaruhi perubahan budaya kinerja organisasi", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0.25, D=0", Penjelasan: "Periksa dan analisis apakah permasalahan pada laporan kinerja ditindaklanjuti pada pelaksanaan program dan kegiatan tahun berikutnya, dengan membandingkan informasi pada laporan kinerja dengan dokumen program dan kegiatan tahun berjalan. Dalami perubahan apa yang dilakukan untuk mendukung kinerja organisasi, adakah terjadi perubahan perilaku atau adanya inovasi yang dilakukan untuk mengatasi kinerja yang tidak tercapai." },
  { ID: "4.a.1", Komponen: "EVALUASI AKUNTABILITAS KINERJA INTERNAL", SubKomponen: "4.a Evaluasi Akuntabilitas Kinerja Internal telah dilaksanakan", Kriteria: "Terdapat pedoman teknis Evaluasi Akuntabilitas Kinerja Internal", Bobot: 2, Aturan_Nilai: "A=2, B=1, C=0", Penjelasan: "Adanya pedoman evaluasi akuntabilitas kinerja internal yang telah diformalkan" },
  { ID: "4.a.2", Komponen: "EVALUASI AKUNTABILITAS KINERJA INTERNAL", SubKomponen: "4.a Evaluasi Akuntabilitas Kinerja Internal telah dilaksanakan", Kriteria: "Evaluasi Akuntabilitas Kinerja Internal telah dilaksanakan pada seluruh unit kerja/perangkat daerah", Bobot: 2, Aturan_Nilai: "A=2, B=1, C=0", Penjelasan: "Terdapat laporan evaluasi akuntabilitas kinerja internal yang dilaksanakan pada seluruh Perangkat Daerah" },
  { ID: "4.a.3", Komponen: "EVALUASI AKUNTABILITAS KINERJA INTERNAL", SubKomponen: "4.a Evaluasi Akuntabilitas Kinerja Internal telah dilaksanakan", Kriteria: "Evaluasi Akuntabilitas Kinerja Internal telah dilaksanakan secara berjenjang", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0", Penjelasan: "Perangkat Daerah melakukan Penilaian Mandiri AKIP sebelum dievaluasi oleh APIP" },
  { ID: "4.b.1", Komponen: "EVALUASI AKUNTABILITAS KINERJA INTERNAL", SubKomponen: "4.b Evaluasi Akuntabilitas Kinerja Internal telah dilaksanakan secara berkualitas dengan Sumber Daya yang memadai", Kriteria: "Evaluasi Akuntabilitas Kinerja Internal telah dilaksanakan sesuai standar", Bobot: 1, Aturan_Nilai: "A=1, B=0.5, C=0", Penjelasan: "Evaluasi telah dilaksanakan sesuai pedoman teknis yang ditentukan mengikuti PermenPANRB atau Perbub/SK yang ditetapkan oleh Pemerintah Kabupaten Mahakam Ulu" },
  { ID: "4.b.2", Komponen: "EVALUASI AKUNTABILITAS KINERJA INTERNAL", SubKomponen: "4.b Evaluasi Akuntabilitas Kinerja Internal telah dilaksanakan secara berkualitas dengan Sumber Daya yang memadai", Kriteria: "Evaluasi Akuntabilitas Kinerja Internal telah dilaksanakan oleh SDM yang memadai", Bobot: 2, Aturan_Nilai: "A=2, B=1, C=0.5, D=0", Penjelasan: "Evaluasi dilakukan oleh Evaluator yang telah mengikuti Diklat Evaluasi Implementasi SAKIP dan/atau telah mengikuti bimtek/workshop/sosialisasi SAKIP, atau penguatan SAKIP yang dilakukan oleh Unit Kerja secara mandiri." },
  { ID: "4.b.3", Komponen: "EVALUASI AKUNTABILITAS KINERJA INTERNAL", SubKomponen: "4.b Evaluasi Akuntabilitas Kinerja Internal telah dilaksanakan secara berkualitas dengan Sumber Daya yang memadai", Kriteria: "Evaluasi Akuntabilitas Kinerja Internal telah dilaksanakan dengan pendalaman yang memadai", Bobot: 2, Aturan_Nilai: "A=2, B=1, C=0", Penjelasan: "Cek apakah data dukung yang disajikan sesuai dengan kriteria pada LKE dan untuk memperdalam evaluasi, evaluator dapat melakukan wawancara dengan unit kerja untuk menyakinkan Evaluasi Akuntabilitas Kinerja Internal" },
  { ID: "4.b.4", Komponen: "EVALUASI AKUNTABILITAS KINERJA INTERNAL", SubKomponen: "4.b Evaluasi Akuntabilitas Kinerja Internal telah dilaksanakan secara berkualitas dengan Sumber Daya yang memadai", Kriteria: "Evaluasi Akuntabilitas Kinerja Internal telah dilaksanakan pada seluruh unit kerja/perangkat daerah", Bobot: 1.5, Aturan_Nilai: "A=1.5, B=1, C=0", Penjelasan: "Telah dilakukan Evaluasi mandiri oleh perangkat daerah sebelum APIP melakukan evaluasi AKIP pada seluruh perangkat daerah" },
  { ID: "4.b.5", Komponen: "EVALUASI AKUNTABILITAS KINERJA INTERNAL", SubKomponen: "4.b Evaluasi Akuntabilitas Kinerja Internal telah dilaksanakan secara berkualitas dengan Sumber Daya yang memadai", Kriteria: "Evaluasi Akuntabilitas Kinerja Internal telah dilaksanakan menggunakan Teknologi Informasi (Aplikasi)", Bobot: 1, Aturan_Nilai: "A=1, B=0", Penjelasan: "Apakah dalam melaksanakan Evaluasi Akuntabilitas Kinerja Internal telah menggunakan teknologi informasi/aplikasi (semua Unit Kerja melakukan Evaluasi Akuntabilitas Kinerja Internal melalui aplikasi)" },
  { ID: "4.c.1", Komponen: "EVALUASI AKUNTABILITAS KINERJA INTERNAL", SubKomponen: "4.c Implementasi SAKIP telah meningkat karena evaluasi Akuntabilitas Kinerja Internal", Kriteria: "Seluruh rekomendasi atas hasil evaluasi akuntablitas kinerja internal telah ditindaklanjuti", Bobot: 3, Aturan_Nilai: "A=3, B=2, C=1, D=0", Penjelasan: "Periksa/analisis tindak lanjut atas rekomendasi LHE AKIP tahun sebelumnya apakah telah dilaksanakan." },
  { ID: "4.c.2", Komponen: "EVALUASI AKUNTABILITAS KINERJA INTERNAL", SubKomponen: "4.c Implementasi SAKIP telah meningkat karena evaluasi Akuntabilitas Kinerja Internal", Kriteria: "Telah terjadi peningkatan implementasi SAKIP dengan melaksanakan tindak lanjut atas rerkomendasi hasil evaluasi akuntablitas Kinerja internal", Bobot: 3, Aturan_Nilai: "A=3, B=2, C=1, D=0", Penjelasan: "Periksa apakah tindaklanjut yang dilakukan satker atas rekomendasi hasil evaluasi akuntabilitas Kinerja internal tahun sebelumnya berpengaruh atas peningkatan implementasi SAKIP di satker." },
  { ID: "4.c.3", Komponen: "EVALUASI AKUNTABILITAS KINERJA INTERNAL", SubKomponen: "4.c Implementasi SAKIP telah meningkat karena evaluasi Akuntabilitas Kinerja Internal", Kriteria: "Hasil Evaluasi Akuntabilitas Kinerja Internal telah dimanfaatkan untuk perbaikan dan peningkatan akuntabilitas kinerja", Bobot: 2, Aturan_Nilai: "A=2, B=1, C=0.5, D=0", Penjelasan: "Analisa rekomendasi yang diberikan dalam LHE apakah terdapat bukti yang nayata bahwa hasil evaluasi telah dimanfaatkan untuk perbaikan dan peningkatan akuntabilitas kinerja" },
  { ID: "4.c.4", Komponen: "EVALUASI AKUNTABILITAS KINERJA INTERNAL", SubKomponen: "4.c Implementasi SAKIP telah meningkat karena evaluasi Akuntabilitas Kinerja Internal", Kriteria: "Hasil dari Evaluasi Akuntabilitas Kinerja Internal telah dimanfaatkan dalam mendukung efektifitas dan efisiensi kinerja", Bobot: 2, Aturan_Nilai: "A=2, B=1, C=0.5, D=0", Penjelasan: "Periksa apakah terdapat belanja-belanja yang tidak mempunyai daya ungkit terhadap pencapaian sasaran dengan mengecek DPA apakah masih terdapat belanja-belanja yang tidak relevan dengan pencapaian sasaran (efisiensi)" },
  { ID: "4.c.5", Komponen: "EVALUASI AKUNTABILITAS KINERJA INTERNAL", SubKomponen: "4.c Implementasi SAKIP telah meningkat karena evaluasi Akuntabilitas Kinerja Internal", Kriteria: "Telah terjadi perbaikan dan peningkatan kinerja dengan memanfaatkan hasil evaluasi akuntablitas kinerja internal", Bobot: 2.5, Aturan_Nilai: "A=2.5, B=1, C=0.5, D=0", Penjelasan: "Periksa apakah terjadi peningkatan capaian indikator kinerja pada Laporan Kinerja yang memberikan dampak perbaikan dan peningkatan kinerja dengan memperhatikan perbandingan capaian kinerja selama 2 tahun (perbandingan dalam persentase capaian) atas semua Indikator Kinerja Utama" }
];

// Fungsi parseRule seperti di Code.gs
export function parseRule(ruleStr) {
  let map = {};
  if (!ruleStr) return map;
  ruleStr.split(',').forEach(p => {
    let kv = p.trim().split('=');
    if (kv.length === 2) map[kv[0].trim()] = parseFloat(kv[1].trim());
  });
  return map;
}

// Fungsi untuk mendapatkan master data dengan RuleMap
export function getMasterData() {
  return MASTER_DATA.map(row => {
    let obj = {
      ID: row.ID,
      Komponen: row.Komponen,
      SubKomponen: row.SubKomponen,
      Kriteria: row.Kriteria,
      Bobot: row.Bobot,
      Aturan_Nilai: row.Aturan_Nilai,
      Penjelasan: row.Penjelasan || '-'
    };
    obj.RuleMap = parseRule(obj.Aturan_Nilai);
    return obj;
  });
}
